name: Bug Report
description: Found something you weren't expecting? Report it here!
labels: kind/bug
body:
- type: markdown
  attributes:
    value: |
      1. Run `update.packages()` and take a moment to check that your issue hasn't been
      reported before.
      2. Use one of our predefined [tasks](https://mlr-org.com/tasks.html) via
      `task = tsk(<id>)`
      3. Please think again if your issue is really related to mlr3 itself or one of the
      mlr3verse packages (e.g. mlr3tuning, mlr3learners, etc)
- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      Please provide a description of your issue here.
- type: textarea
  id: code
  attributes:
    label: Minimal reproducible example
    description: |
      Provide a **minimal** reproducible example, i.e. a simplified version of your problem that allows to reproduce your problem in a clean environment.
      You can use the [reprex](https://github.com/tidyverse/reprex) package to do so.
      Please include the session info using `reprex::reprex(..., session_info = TRUE)`
