name: Bug Report
description: Found something you weren't expecting? Report it here!
labels: kind/bug
body:
- type: markdown
  attributes:
    value: |
      1. Make sure you are using the latest release and
         take a moment to check that your issue hasn't been reported before.
      2. Please give all relevant information below for bug reports.
      3. Please use tasks that come with mlr3 and not your personal data.
- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      Please provide a description of your issue here.

