name: Bug Report
description: Found something you weren't expecting? Report it here!
labels: kind/bug
body:
- type: markdown
  attributes:
    value: |
      * Before submitting a bug, please run `update.packages()` and see if the bug still exists.
      * Please check whether your problem has already been mentioned on GitHub or Stack Overflow
      * Please think again if your issue is really related to mlr3 itself or one of the mlr3verse packages (e.g. mlr3tuning, mlr3learners, ...).
      * When reporting a bug, please use one of our predefined [tasks](https://mlr-org.com/tasks.html) via `task = tsk(<id>)`.
      * To create a reproducible example, do the following:
          1. Copy the code that includes the problem you want to report.
          2. Run `reprex::reprex(session_info = TRUE, style = TRUE)`.
          3. The code is now on your clipboard and you can paste it into this issue form. If
          it differs from what you were expecting, your example is likely not reproducible.



- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      Please provide a description of your issue here.
- type: textarea
  id: code
  attributes:
    label: Minimal reproducible example
    description: |
      Provide a [MWE](https://stackoverflow.com/help/minimal-reproducible-example), i.e. a simplified version of your problem that allows to reproduce your problem in a clean environment. Please also include the `sessionInfo()`. We recommend using the [reprex](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) package to do.

      so using `reprex::reprex(..., session_info = TRUE)`.
